### ISSUE TITLE
Object문제.

### ISSUE THREAD

**Issue by bjrambo** [largeden/full_search#2]
https://github.com/largeden/full_search/blob/0b3861307802cd001effca103818ab2c4f3e59bd/full_search.model.php#L105

해당 파일에서는 BaseObject의 대한 옵션만 들어가 있습니다.

BaseObject를 업데이트 하지 않은 기존 코어에서는 해당 값이 fasle만 나올 것 같습니다.

모듈의 class 파일에는 정상적으로 잘 대응 하신 것 같아요.

https://github.com/bjrambo/attendance/blob/master/attendance.class.php#L513

다만 위 링크와 같이 Object를 생성하는 곳에서 return new Object를 사용하는 부분이 있을때 
$this->makeObject(-1, '에러메세지');
형태로 사용할수 있도록 해주시는 것도 좋을 것 같습니다.

**Comment by largeden** [comment]
@bjrambo 내부코드를 최신 버전으로 교체 적용하겠습니다.
의견 고맙습니다. :)
